version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo prebuild stage
      
  build:
    commands:
      - docker compose up -d
  post_build:
    commands:
      - echo build end