version: 0.2
phases:
  pre_build:
    commands:
      - echo prebuild stage
      
  build:
    commands:
      - docker compose up -f docker-compose.yml
  post_build:
    commands:
      - echo build end