version: 0.2
phases:
  pre_build:
    commands:
      - echo prebuild stage
      - docker info
      - docker version
     
      
  build:
    commands:
     
  post_build:
    commands:
      - echo build end